services:
  - type: web
    name: restaurant-management-system-server
    runtime: node
    plan: free
    buildCommand: npm run render-build
    preDeployCommand: npm run db:deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
