import express from "express";
import { AuthRoute } from "../module/auth/auth.route";
import { UserRoutes } from "../module/user/user.route";
import { FoodCategoryRoute } from "../module/foodCategory/foodCategory.route";
import { FoodRoute } from "../module/food/food.route";
import { PropertyRoute } from "../module/property/property.route";
import { DineLocationRoute } from "../module/dineLocation/dineLocation.route";
import { DineTableRoute } from "../module/dineTable/dineTable.route";
import { WaiterRoute } from "../module/waiter/waiter.route";
import { WorkPeriodRoute } from "../module/workPeriod/workPeriod.route";
import { OrderRoute } from "../module/order/order.route";
import { DashboardRoute } from "../module/dashboard/dashboard.route";
import { InventoryRoute } from "../module/inventory/inventory.route";
import { FinanceRoute } from "../module/finance/finance.route";
import { HrRoute } from "../module/hr/hr.route";
import { BankRoute } from "../module/bank/bank.route";
import { DueRoute } from "../module/due/due.route";
import { ReportRoute } from "../module/report/report.route";
import { FloorPlanRoute } from "../module/floorPlan/floorPlan.route";

const router = express.Router();

router.use("/auth", AuthRoute);
router.use("/users", UserRoutes);
router.use("/food-categories", FoodCategoryRoute);
router.use("/foods", FoodRoute);
router.use("/property", PropertyRoute);
router.use("/dine-locations", DineLocationRoute);
router.use("/dine-tables", DineTableRoute);
router.use("/dine/floor-plan", FloorPlanRoute);
router.use("/waiters", WaiterRoute);
router.use("/work-periods", WorkPeriodRoute);
router.use("/orders", OrderRoute);
router.use("/dashboard", DashboardRoute);
router.use("/inventory", InventoryRoute);
router.use("/finance", FinanceRoute);
router.use("/hr", HrRoute);
router.use("/bank", BankRoute);
router.use("/due", DueRoute);
router.use("/reports", ReportRoute);

export const IndexRoute = router;
